# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller:
        enabled:              '%kernel.debug%'
        profiler:             false
#    read_from:            '%assetic.read_from%'
    write_to:             '%kernel.root_dir%/../web'
    java: /usr/bin/java
    node: /usr/bin/node
    node_paths:
        - "%kernel.root_dir%/../node_modules"  
        - /usr/lib/node_modules
        - /usr/lib/nodejs
        - /usr/share/javascript
    ruby: /usr/bin/ruby
    filters:
#        autoprefixer: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        coffee: ~
        compass:
            bin: /usr/local/bin/compass
        csscachebusting: ~
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed-0.4.5.jar"
        cssimport: ~
        cssmin: ~
        cssrewrite: ~
        dart:
            bin: /usr/lib/dart/bin/dart2js
        emberprecompile:
            bin: /usr/bin/ember
        gss:
            jar: "%kernel.root_dir%/Resources/java/closure-stylesheets-library.jar"
        handlebars: ~
        jpegoptim: ~
        jpegtran: ~
        jsmin: ~
        jsminplus: ~
        jsqueeze: ~
        less:
            bin: "%kernel.root_dir%/../node_modules/.bin/lessc"
        minifycsscompressor: ~
        optipng: ~
        packager: ~
        packer: ~
        phpcssembed: ~
        pngout:
            bin: "%kernel.root_dir%/../node_modules/.bin/pngout"
#            bin: "%kernel.root_dir%/../bin/pngout"
        reactjsx:
            bin: /usr/bin/jsx
        roole: ~
        sass:
            bin: "%kernel.root_dir%/../node_modules/.bin/node-sass"
#            bin: /usr/local/bin/sass
        scss: ~
        sprockets:
            lib: /usr/local/bin/sprockets
        typescript: ~
        uglifycss:
            # on utilise le uglifycss installé localement
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifycss"
        uglifyjs2:
            # on utilise le uglifyjs installé localement
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifyjs"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
    bundles:
        - IlcfranceWorldspeakSharedDataBundle
        - IlcfranceWorldspeakSharedResBundle
        - IlcfranceWorldspeakAdminFrontBundle
        - IlcfranceWorldspeakAdminSecurityBundle
        - IlcfranceWorldspeakTeacherFrontBundle
        - IlcfranceWorldspeakTeacherSecurityBundle
        - IlcfranceWorldspeakTraineeFrontBundle
        - IlcfranceWorldspeakTraineeSecurityBundle

    assets:
        
        # bootstrap_css
        bootstrap_css:
            inputs: "%kernel.root_dir%/../web/res/bower_components/bootstrap3/less/bootstrap.less"
            filters:
                - less
                - cssrewrite
            output: 'css/bootstrap.css'

        # Jquery
        jquery3:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery3/dist/jquery.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery3.min.js'

        # Jquery
        jquery2:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery2/jquery.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery2.min.js'

        # Jquery
        jquery1:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery1/dist/jquery.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery.min.js'

        # bootstrap_min_js
        bootstrap_min_js:
            inputs:
                - "%kernel.root_dir%/../web/res/bower_components/bootstrap3/dist/js/bootstrap.js"
                - "%kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js"
            filters:
                - uglifyjs2
            combine: true
            output: 'js/bootstrap.min.js'


