# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
#    spool:     { type: service, id: snc_redis.swiftmailer.spool }

