parameters:
    schemes: https
    domain: worldspeak.ilcfrance.com
    mail_from:          donotreply@ILCFrance.com
    mail_from_name:          ILCWorldSpeak
    sitename:                  "WorldSpeak.ILCFrance.com"
    mailer_transport: smtp
    siteversion: 1.0.2
