admin_security_logout:
    path:  /logout

admin_security_login:
    path:  /login
    defaults: { _controller: "IlcfranceWorldspeakAdminSecurityBundle:Security:login" }

admin_security_check:
    path:  /login_check
    methods: [POST]

admin_security_lost_username:
    path:  /dontRememberUsername
    defaults: { _controller: "IlcfranceWorldspeakAdminSecurityBundle:Security:dontRememberUsername" }

admin_security_lost_password:
    path:  /lostPassword
    defaults: { _controller: "IlcfranceWorldspeakAdminSecurityBundle:Security:lostPassword" }

admin_security_lost_genpassword:
    path:  /genNewPassword/{id}/{code}
    defaults: { _controller: "IlcfranceWorldspeakAdminSecurityBundle:Security:genNewPassword" }

admin_security_profile:
    path:  /myProfile
    defaults: { _controller: "IlcfranceWorldspeakAdminSecurityBundle:Security:myProfile" }


admin_security_profile_avatar:
    path:  /myAvatar
    defaults: { _controller: "IlcfranceWorldspeakAdminSecurityBundle:Security:myAvatar" }