parameters:
#    com_ilcfrance_worldspeak_admin_security.example.class: Ilcfrance\Worldspeak\Admin\SecurityBundle\Example

services:
#    com_ilcfrance_worldspeak_admin_security.example:
#        class: %com_ilcfrance_worldspeak_admin_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    com_ilcfrance_worldspeak_admin_security.login_listener:
        class: Ilcfrance\Worldspeak\Admin\SecurityBundle\Listener\LoginSuccess
        arguments: ["@doctrine"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    com_ilcfrance_worldspeak_admin_security.activity_listener:
        class: Ilcfrance\Worldspeak\Admin\SecurityBundle\Listener\Activity
        arguments: ['@security.token_storage', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    com_ilcfrance_worldspeak_admin_security.locale_kernel_request_listener:
        class: Ilcfrance\Worldspeak\Admin\SecurityBundle\Listener\Locale
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocale }
