parameters:
#    com_ilcfrance_worldspeak_trainee_front.example.class: Ilcfrance\Worldspeak\Trainee\FrontBundle\Example

services:
#    com_ilcfrance_worldspeak_trainee_front.example:
#        class: %com_ilcfrance_worldspeak_trainee_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
